### ISSUE TITLE
ATC error after deploying to ABAP system

### ISSUE THREAD

**Issue by rameshputta79** [marianfoo/ui5-cc-spreadsheetimporter#363]
Hello,
I used the excel upload tool ( cc.excelUpload.v0_19_0 ) in my app and everything seems to be working fine.
But when i deployed the app to the ABAP system I get the following ATC error, Please let me know the best way to handle this.
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/121116258/4c4de119-093d-4e7a-94e9-74d245fefb66)

**Comment by marianfoo** [comment]
Please use the bug template.
Did you use central or in-app deployment?
Thanks

**Comment by marianfoo** [comment]
I just had a look again and in the Note [2588088](https://me.sap.com/notes/2588088/E) this is suggested as resolution:
>Run the following report manually : /UI5/APP_INDEX_CALCULATE 

If this is not the resolution, this is a false positive because you defined the component in the manifest.  
The default usage is to use a deployed component, but guess you using the component from the app.  
So the test is looking for the component on the local system but can not find it because it is not deployed. 

Can you confirm this?

**Comment by marianfoo** [comment]
Do you need more support on this?

**Comment by rameshputta79** [comment]
thanks Marian, I am ok for now. I will reach out if I need help. thanks

**Comment by marianfoo** [comment]
I got a report that a different company has the same message.
What SAP System is this error from?

As a "Hotfix" you can deploy the component with the version (in this case v0.19.0) to the SAP System like described here:
https://docs.spreadsheet-importer.com/pages/CentralDeployment/

Unfortunately you have to do that for every version.  
I´ll check if there is a different solution

**Comment by marianfoo** [comment]
Still a workaround and not a solution, but that works adding this in the `manifest.json`:  
```json
"sap.app": {
  "embeds": ["thirdparty/customControl/spreadsheetImporter/v0_29_0"]
}
```

documented here:
https://docs.spreadsheet-importer.com/pages/GettingStarted/#decentralized-deployment
