### ISSUE TITLE
Feature Request: Importing previously exported XLSX files

### ISSUE THREAD

**Issue by MARCxGAMBIT** [marianfoo/ui5-cc-spreadsheetimporter#399]
Hey, at the moment it is not possible to export a table, make some modifications to the content and then import it using this control.

The standard Fiori Export uses the human readable labels as Column header while the importer expects the technical name of the property in square brackets.

While an end user label is not necessarily a unique key do you think it'd be possible to implement some kind of fallback where it tries to find the next best property for a label?

**Comment by marianfoo** [comment]
Hi Marc,
currently there is no fallback because the field matching is done explicit with this config:  
https://docs.spreadsheet-importer.com/pages/Configuration/#fieldmatchtype

When you change this to `label` it will match the label. In theory you can then download the excel file and upload it again. You would copy the data, not update it (a feature reserved for the Pro version).

You can use both `fieldMatchType` at the same time.  
You can set `labelTypeBrackets` as option and set `showOptions` to `true` and `availableOptions` to `["fieldMatchType"]`.  
No the user can change between those options.

I don't like to "guess" which label belongs to which property. Either I am 100% sure or it was just not found. 
I wanted to deprecate the `label` option already, but the use case you describe is the only valid one for this option.

**Comment by MARCxGAMBIT** [comment]
Thanks for the insight!
